title: Stack Problems
description: My Personal Stack Problems
author: Андрей Лесько
github: https://github.com/JotBet/jotbet.github.io
about: "Обкатываю буки"
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar-img.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-vimeo
      link: "https://vimeo.com/obkat"
    - icon: fa-youtube
      link: "https://youtube.com/obkat"
    - icon: fa-twitch
      link: "https://www.twitch.tv/obkat"
    # - icon: fa-linkedin
    #   link: "https://www.linkedin.com/in/summonagus"
    # - icon: fa-stack-exchange
    #   link: "#"
    # - icon: fa-github
    #   link: "https://github.com/agusmakmun"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: Главная
      url: /index.html
    - text: Видео
      url: /video/
    - text: Oбо мне
      url: /about/
    - text: Контакт
      url: /contact/


url: "https://agusmakmun.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown

plugins:
  - jekyll-paginate

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

future: true